# docker-compose.yml
version: '3'

services:
  backend:
    build:
      context: ./MyServer
      dockerfile: ./Dockerfile
    image: "dashboard-backend"
    stdin_open: true
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./MyFront
      dockerfile: ./Dockerfile
    image: "dashboard-frontend"
    ports:
      - "3000:3000"
    links:
      - "backend:be"
